### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by CalCraven** [GOMC-WSU/MoSDeF-GOMC#77]
I think some of the text for the readme could get updated with versions of GMSO/MoSDeF being more stable.

"The original version of MoSDeF-GOMC, which uses Parmed as the software backend, will be deprecated by December 2022. This Parmed version is already replaced with the new MoSDeF-GOMC version, which uses MoSDeF's GMSO software as the new backend. We recommend that the new GMSO version of MoSDeF-GOMC be used because it has many new features, and the Parmed is no longer supported."

**Comment by bc118** [comment]
Done
